version: '3.9'
services:
  web:
    build: ./app
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      - TWILIO_TEST_NUMBER=${TWILIO_TEST_NUMBER}

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: zorrito
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zorrito
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
