services:
  web:
    build: ./app
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      - TWILIO_TEST_NUMBER=${TWILIO_TEST_NUMBER}
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: zorrito
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zorrito
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: ./app
    command: celery -A nws_alert_poller worker --loglevel=info
    depends_on:
      - web
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    user: "nobody"

  beat:
    build: ./app
    command: celery -A nws_alert_poller beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    depends_on:
      - web
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    user: "nobody"
    volumes:
      - /tmp:/tmp

volumes:
  pgdata:
