services:
  web:
    build: ./app
    env_file: .env
    ports:
      - "8181:8181"
    command: sh -c "until pg_isready -h db -U zorrito; do sleep 1; done; python3 && gunicorn main:app --bind 0.0.0.0:8181"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
      - TWILIO_TEST_NUMBER=${TWILIO_TEST_NUMBER}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:14
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zorrito"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    expose:
      - "6379"
    restart: unless-stopped
    networks:
      - internal

  worker:
    build: ./app
    command: celery -A celery_scheduler worker --loglevel=info
    depends_on:
      - web
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    user: "nobody"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - internal

  beat:
    build: ./app
    command: celery -A celery_scheduler beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    depends_on:
      - web
      - redis
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    user: "nobody"
    volumes:
      - /tmp:/tmp
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - internal

  libretranslate:
    image: libretranslate/libretranslate
    expose:
      - "5000"
    environment:
      - LT_LOAD_ONLY=en,es,so,ar,fr,rw,vi,ne,te,tr,ps,sw,mai,ja,zh
    restart: unless-stopped

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
