
version: '3.9'
services:
  web:
    build: ./app
    ports:
      - "8181:8181"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: zorrito
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zorrito
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
