INSERT INTO state_alerts (fips, name) VALUES (0, 'UNITED STATES');
INSERT INTO state_alerts (fips, name) VALUES (1000, 'ALABAMA');
INSERT INTO state_alerts (fips, name) VALUES (2000, 'ALASKA');
INSERT INTO state_alerts (fips, name) VALUES (4000, 'ARIZONA');
INSERT INTO state_alerts (fips, name) VALUES (5000, 'ARKANSAS');
INSERT INTO state_alerts (fips, name) VALUES (6000, 'CALIFORNIA');
INSERT INTO state_alerts (fips, name) VALUES (8000, 'COLORADO');
INSERT INTO state_alerts (fips, name) VALUES (9000, 'CONNECTICUT');
INSERT INTO state_alerts (fips, name) VALUES (10000, 'DELAWARE');
INSERT INTO state_alerts (fips, name) VALUES (11000, 'DISTRICT OF COLUMBIA');
INSERT INTO state_alerts (fips, name) VALUES (12000, 'FLORIDA');
INSERT INTO state_alerts (fips, name) VALUES (13000, 'GEORGIA');
INSERT INTO state_alerts (fips, name) VALUES (15000, 'HAWAII');
INSERT INTO state_alerts (fips, name) VALUES (16000, 'IDAHO');
INSERT INTO state_alerts (fips, name) VALUES (17000, 'ILLINOIS');
INSERT INTO state_alerts (fips, name) VALUES (18000, 'INDIANA');
INSERT INTO state_alerts (fips, name) VALUES (19000, 'IOWA');
INSERT INTO state_alerts (fips, name) VALUES (20000, 'KANSAS');
INSERT INTO state_alerts (fips, name) VALUES (21000, 'KENTUCKY');
INSERT INTO state_alerts (fips, name) VALUES (22000, 'LOUISIANA');
INSERT INTO state_alerts (fips, name) VALUES (23000, 'MAINE');
INSERT INTO state_alerts (fips, name) VALUES (24000, 'MARYLAND');
INSERT INTO state_alerts (fips, name) VALUES (25000, 'MASSACHUSETTS');
INSERT INTO state_alerts (fips, name) VALUES (26000, 'MICHIGAN');
INSERT INTO state_alerts (fips, name) VALUES (27000, 'MINNESOTA');
INSERT INTO state_alerts (fips, name) VALUES (28000, 'MISSISSIPPI');
INSERT INTO state_alerts (fips, name) VALUES (29000, 'MISSOURI');
INSERT INTO state_alerts (fips, name) VALUES (30000, 'MONTANA');
INSERT INTO state_alerts (fips, name) VALUES (31000, 'NEBRASKA');
INSERT INTO state_alerts (fips, name) VALUES (32000, 'NEVADA');
INSERT INTO state_alerts (fips, name) VALUES (33000, 'NEW HAMPSHIRE');
INSERT INTO state_alerts (fips, name) VALUES (34000, 'NEW JERSEY');
INSERT INTO state_alerts (fips, name) VALUES (35000, 'NEW MEXICO');
INSERT INTO state_alerts (fips, name) VALUES (36000, 'NEW YORK');
INSERT INTO state_alerts (fips, name) VALUES (37000, 'NORTH CAROLINA');
INSERT INTO state_alerts (fips, name) VALUES (38000, 'NORTH DAKOTA');
INSERT INTO state_alerts (fips, name) VALUES (39000, 'OHIO');
INSERT INTO state_alerts (fips, name) VALUES (40000, 'OKLAHOMA');
INSERT INTO state_alerts (fips, name) VALUES (41000, 'OREGON');
INSERT INTO state_alerts (fips, name) VALUES (42000, 'PENNSYLVANIA');
INSERT INTO state_alerts (fips, name) VALUES (44000, 'RHODE ISLAND');
INSERT INTO state_alerts (fips, name) VALUES (45000, 'SOUTH CAROLINA');
INSERT INTO state_alerts (fips, name) VALUES (46000, 'SOUTH DAKOTA');
INSERT INTO state_alerts (fips, name) VALUES (47000, 'TENNESSEE');
INSERT INTO state_alerts (fips, name) VALUES (48000, 'TEXAS');
INSERT INTO state_alerts (fips, name) VALUES (49000, 'UTAH');
INSERT INTO state_alerts (fips, name) VALUES (50000, 'VERMONT');
INSERT INTO state_alerts (fips, name) VALUES (51000, 'VIRGINIA');
INSERT INTO state_alerts (fips, name) VALUES (53000, 'WASHINGTON');
INSERT INTO state_alerts (fips, name) VALUES (54000, 'WEST VIRGINIA');
INSERT INTO state_alerts (fips, name) VALUES (55000, 'WISCONSIN');
INSERT INTO state_alerts (fips, name) VALUES (56000, 'WYOMING');
